"""empty message

Revision ID: 19ad464e30c2
Revises: 
Create Date: 2023-06-14 10:21:40.102696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ad464e30c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplications',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coins',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disconts',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('powers',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocodes',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('start',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=128), nullable=True),
    sa.Column('start_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('category_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('kolvo', sa.VARCHAR(length=128), nullable=True),
    sa.Column('call_me', sa.VARCHAR(length=128), nullable=True),
    sa.Column('discont', sa.VARCHAR(length=5), nullable=True),
    sa.Column('power', sa.VARCHAR(length=128), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=5), nullable=True),
    sa.Column('coin', sa.VARCHAR(length=24), nullable=True),
    sa.Column('cost_electricity', sa.VARCHAR(length=128), nullable=True),
    sa.Column('hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('potreb', sa.VARCHAR(length=128), nullable=True),
    sa.Column('komm', sa.VARCHAR(length=128), nullable=True),
    sa.Column('promo', sa.VARCHAR(length=128), nullable=True),
    sa.Column('date', sa.VARCHAR(length=28), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('start')
    op.drop_table('promocodes')
    op.drop_table('powers')
    op.drop_table('disconts')
    op.drop_table('currencies')
    op.drop_table('coins')
    op.drop_table('categories')
    op.drop_table('aplications')
    op.drop_table('admin')
    # ### end Alembic commands ###
